<template>
  <section id="faq" class="py-24 bg-slate-50 relative overflow-hidden">
    <!-- 背景装饰：柔和的环形渐变 -->
    <div class="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-96 h-96 bg-indigo-100/40 rounded-full blur-3xl"></div>

    <div class="max-w-4xl mx-auto px-6 relative">
      <!-- Header Area -->
      <div class="text-center mb-16">
        <p class="text-sm font-bold tracking-[0.2em] text-indigo-600 uppercase mb-4">
          Knowledge Base
        </p>
        <h2 class="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight mb-6">
          Common Questions about <span class="text-indigo-600">Wan 2.7 AI Video Generator</span>
        </h2>
        <p class="text-lg text-slate-600">
          Everything you need to know about mastering our multimodal AI engine.
        </p>
      </div>

      <!-- FAQ Accordion -->
      <div class="space-y-4">
        <div 
          v-for="(item, index) in faqs" 
          :key="index" 
          class="group bg-white rounded-2xl border border-slate-200 overflow-hidden hover:border-indigo-300 transition-all duration-300"
        >
          <details class="group">
            <summary class="flex items-center justify-between p-6 cursor-pointer list-none">
              <h3 class="text-lg font-bold text-slate-900 group-hover:text-indigo-600 transition-colors pr-8">
                {{ item.q }}
              </h3>
              <!-- 动态旋转图标 -->
              <div class="relative flex-shrink-0 w-6 h-6">
                <div class="absolute inset-0 bg-slate-100 group-hover:bg-indigo-50 rounded-full transition-colors"></div>
                <svg xmlns="http://www.w3.org/2000/svg" class="absolute inset-0 m-auto h-4 w-4 text-slate-500 group-hover:text-indigo-600 transition-transform duration-300 group-open:rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
              </div>
            </summary>
            <div class="px-6 pb-6 animate-fadeIn">
              <div class="pt-2 border-t border-slate-100">
                <p class="text-slate-600 leading-relaxed text-base">
                  <span v-html="highlightKeyword(item.a)"></span>
                </p>
              </div>
            </div>
          </details>
        </div>
      </div>

      <!-- Bottom Support CTA -->
      <div class="mt-16 p-8 bg-slate-900 rounded-3xl text-center">
        <h4 class="text-white font-bold text-xl mb-2">Still have more questions?</h4>
        <p class="text-slate-400 mb-6 text-sm">Our technical team is ready to help you push your creative boundaries.</p>
        <a href="mailto:support@seedance2pro.net" class="inline-flex items-center gap-2 text-indigo-400 font-bold hover:text-indigo-300 transition-colors">
          Contact Our Support Team
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
          </svg>
        </a>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const faqs = [
  {
    q: 'What makes Wan 2.7 AI Video Generator different from other tools?',
    a: 'Unlike traditional tools that rely solely on text prompts, Wan 2.7 AI Video Generator is a truly multimodal engine. It allows you to use images, videos, and audio as direct references to dictate the exact style, identity, and motion of your cinematic results.',
  },
  {
    q: 'How does this model handle character consistency?',
    a: 'Consistency is our core strength. Through our specialized Identity Persistence mechanism, you can tag a reference image and Wan 2.7 AI Video Generator will lock that visual DNA across every frame, eliminating character flicker.',
  },
  {
    q: 'Can I use Wan 2.7 AI Video Generator to extend existing videos?',
    a: 'Absolutely. Our "Video Extension" suite analyzes your original footage to generate logical subsequent actions with perfect narrative continuity, acting like a camera that keeps rolling beyond the original clip.',
  },
  {
    q: 'Are the videos cleared for commercial use?',
    a: 'Yes. All videos generated by Wan 2.7 AI Video Generator under a paid tier include full commercial rights. You retain 100% ownership, making your content ready for social monetization or client delivery.',
  },
]

// 简单的关键词高亮函数
const highlightKeyword = (text: string) => {
  return text.replace(/Wan 2.7 AI Video Generator/g, '<span class="font-semibold text-slate-900 underline decoration-indigo-200 underline-offset-4">Wan 2.7 AI Video Generator</span>');
}
</script>

<style scoped>
/* 自定义详情展开动画 */
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(-10px); }
  to { opacity: 1; transform: translateY(0); }
}
.animate-fadeIn {
  animation: fadeIn 0.4s ease-out forwards;
}

/* 隐藏 details 默认箭头 */
summary::-webkit-details-marker {
  display: none;
}

h2 {
  text-wrap: balance;
}
</style>