<template>
  <section class="py-24 bg-gradient-to-br from-white via-blue-50 to-purple-50 relative overflow-hidden">
    <!-- 背景装饰 -->
    <div class="absolute inset-0 opacity-20">
      <div
        class="absolute top-1/4 left-1/5 w-80 h-80 bg-gradient-to-br from-blue-200 to-indigo-200 rounded-full blur-3xl"
      ></div>
      <div
        class="absolute bottom-1/4 right-1/5 w-72 h-72 bg-gradient-to-tr from-indigo-200 to-purple-200 rounded-full blur-3xl"
      ></div>
    </div>

    <div class="max-w-5xl mx-auto px-6 relative z-10">
      <!-- 标题 -->
      <div class="text-center mb-14">
        <h2
          class="text-3xl md:text-4xl lg:text-5xl font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 bg-clip-text text-transparent mb-5 leading-tight"
        >
          Frequently Asked Questions about Wan 2.6
        </h2>
      </div>

      <!-- FAQ Items -->
      <div class="space-y-6">
        <div 
          v-for="(faq, index) in faqs" 
          :key="index"
          class="group bg-white/80 backdrop-blur-sm rounded-2xl overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 border border-purple-100/60"
          :class="faq.isOpen ? 'ring-2 ring-purple-200 shadow-xl' : ''"
        >
          <button
            @click="toggleFaq(index)"
            class="w-full px-6 md:px-8 py-5 md:py-6 text-left flex items-center justify-between hover:bg-purple-50/50 transition-all duration-300 group"
          >
            <h3 class="text-lg md:text-xl font-bold text-gray-900 pr-6 group-hover:text-purple-600 transition-colors duration-300">
              {{ faq.question }}
            </h3>
            <div class="flex-shrink-0">
              <div 
                :class="[
                  'w-10 h-10 rounded-full flex items-center justify-center transition-all duration-300',
                  faq.isOpen 
                    ? 'bg-purple-100 text-purple-600 rotate-180' 
                    : 'bg-gray-100 text-gray-500 group-hover:bg-purple-100 group-hover:text-purple-600'
                ]"
              >
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
              </div>
            </div>
          </button>
          <div 
            :class="[
              'overflow-hidden transition-all duration-500 ease-in-out',
              faq.isOpen ? 'max-h-[800px] opacity-100' : 'max-h-0 opacity-0'
            ]"
          >
            <div class="px-6 md:px-8 pb-6 md:pb-8">
              <div class="w-full h-px bg-gradient-to-r from-purple-200 to-indigo-200 mb-6"></div>
              <p class="text-gray-700 leading-relaxed text-base md:text-lg">
                {{ faq.answer }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const faqs = ref([
  {
    question: 'What is Wan 2.6 used for?',
    answer: 'Wan 2.6 is used to generate AI videos with clearer storytelling, stable characters, and synchronized audio, making it suitable for narrative and character-driven content.',
    isOpen: false
  },
  {
    question: 'How is Wan 2.6 different from Wan 2.5?',
    answer: 'Wan 2.6 removes several limitations found in Wan 2.5, including short clip length, weaker multi-shot structure, and separate audio generation, enabling more complete scenes.',
    isOpen: false
  },
  {
    question: 'Does Wan 2.6 support reference-based video generation?',
    answer: 'Yes. Wan 2.6 can generate videos by referencing input videos, images, or characters, helping preserve visual identity and voice consistency across scenes.',
    isOpen: false
  },
  {
    question: 'Can Wan 2.6 create multi-shot or story-like videos?',
    answer: 'Yes. Wan 2.6 is designed to generate structured, multi-shot videos rather than isolated clips, making stories easier to follow.',
    isOpen: false
  },
  {
    question: 'How long are videos generated by Wan 2.6?',
    answer: 'Wan 2.6 supports video generation up to 15 seconds per output, allowing creators to include more narrative detail in a single generation.',
    isOpen: false
  },
  {
    question: 'Is audio generated together with the video?',
    answer: 'Yes. Wan 2.6 generates audio and visuals together, which reduces synchronization issues and removes the need for separate audio editing tools.',
    isOpen: false
  },
  {
    question: 'Are credits deducted if a generation fails?',
    answer: 'No. Credits are only deducted after a successful generation. Failed or interrupted generations are not charged.',
    isOpen: false
  },
  {
    question: 'Can I use Wan 2.6 videos for commercial projects?',
    answer: 'Yes. Videos generated using paid credits can be used for commercial purposes, including marketing, social media, and creative projects.',
    isOpen: false
  },
  {
    question: 'Do purchased credits expire?',
    answer: 'No. Purchased credits do not expire and remain available until they are used.',
    isOpen: false
  },
  {
    question: 'Do I need editing experience to use Wan 2.6?',
    answer: 'No. Wan 2.6 is designed to reduce manual editing by generating more complete videos directly from prompts and references.',
    isOpen: false
  }
])

const toggleFaq = (index: number) => {
  faqs.value[index].isOpen = !faqs.value[index].isOpen
}
</script>

<style scoped>
</style>

