<template>
  <section id="hero" class="py-20">
    <div class="max-w-7xl mx-auto px-6">
      <PageHero 
      title="Cinematic AI Video, Generated by Wan 2.2 Plus"
      subtitle="
      Unleash cinematic visuals and realistic motion with powerful prompt control. The ideal AI video generator for creators and marketers."
    />
      
                    <!-- Interactive Form and Preview -->
        <div class="grid lg:grid-cols-2 gap-12 items-stretch">
                   <!-- Left Column: Form -->
                    <div class="bg-white rounded-xl border border-gray-200 shadow-lg p-8">
                        <form @submit.prevent="handleGenerate" class="space-y-3">
                         <!-- Mode Switcher -->
             <div class="pb-2 border-b border-gray-200">
               <label class="block text-sm font-medium text-gray-700 mb-2">Generation Mode</label>
               <div class="flex bg-gray-100 rounded-lg p-1">
                 <button 
                   type="button" 
                   :class="[
                     'flex-1 py-2.5 px-4 rounded-md font-medium transition-all duration-200',
                     activeMode === 'text-to-video' 
                       ? 'bg-white text-blue-dark shadow-sm' 
                       : 'text-gray-500 hover:text-gray-700'
                   ]"
                   @click="switchMode('text-to-video')"
                 >
                   Text to Video
                 </button>
                 <button 
                   type="button" 
                   :class="[
                     'flex-1 py-2.5 px-4 rounded-md font-medium transition-all duration-200',
                     activeMode === 'image-to-video' 
                       ? 'bg-white text-blue-dark shadow-sm' 
                       : 'text-gray-500 hover:text-gray-700'
                   ]"
                   @click="switchMode('image-to-video')"
                 >
                   Image to Video
                 </button>
               </div>
             </div>
            
                         <!-- Prompt Input -->
             <div class="pb-2 border-b border-gray-200">
               <label class="block text-sm font-medium text-gray-700 mb-2">Prompt</label>
               <textarea 
                 v-model="prompt"
                 rows="3" 
                 class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-dark focus:border-blue-dark resize-none transition-colors"
                 placeholder="e.g., A hyperrealistic shot of a hummingbird hovering over a flower, slow motion"
               ></textarea>
             </div>
            
                         <!-- Image Upload Section -->
             <div v-show="activeMode === 'image-to-video'" class="pb-2 border-b border-gray-200">
               <label class="block text-sm font-medium text-gray-700 mb-2">Upload Image</label>
                                <label 
                   for="image-upload" 
                   class="flex flex-col items-center justify-center w-full h-24 border-2 border-dashed border-gray-300 rounded-lg cursor-pointer hover:border-blue-dark transition-colors"
                 >
                 <svg class="w-6 h-6 text-gray-400 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                   <polyline points="17 8 12 3 7 8"></polyline>
                   <line x1="12" y1="3" x2="12" y2="15"></line>
                 </svg>
                 <p class="text-sm text-gray-500">Click to upload or drag and drop</p>
               </label>
               <input type="file" id="image-upload" class="hidden" @change="handleImageUpload" accept="image/*">
             </div>
                                                                                                   <!-- Resolution Selection -->
                          <div class="pb-2 border-b border-gray-200">
                <label class="block text-sm font-medium text-gray-700 mb-2">Resolution</label>
                <div class="grid grid-cols-2 gap-4">
                  <!-- Quality Selection -->
                  <div>
                    <label class="block text-xs font-medium text-blue-resolutionlabel mb-2">Quality</label>
                    <select 
                      v-model="selectedResolution" 
                      class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-dark focus:border-blue-dark transition-colors text-blue-resolutionoption"
                    >
                      <option value="480p" class="text-blue-resolutionoptionselected">480P (20 Credits)</option>
                      <option value="1080p" class="text-blue-resolutionoptionselected">1080P (100 Credits)</option>
                    </select>
                  </div>
                  
                  <!-- Aspect Ratio Selection -->
                  <div v-if="activeMode === 'text-to-video'">
                    <label class="block text-xs font-medium text-blue-aspectlabel mb-2">Aspect Ratio</label>
                    <select 
                      v-model="selectedAspectRatio" 
                      class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-dark focus:border-blue-dark transition-colors text-blue-aspectoption"
                    >
                      <option v-if="selectedResolution === '480p'" value="1:1" class="text-blue-aspectoptionselected">1:1 (832×480)</option>
                      <option v-if="selectedResolution === '480p'" value="16:9" class="text-blue-aspectoptionselected">16:9 (624×624)</option>
                      <option v-if="selectedResolution === '480p'" value="9:16" class="text-blue-aspectoptionselected">9:16 (480×832)</option>
                      <option v-if="selectedResolution === '1080p'" value="16:9" class="text-blue-aspectoptionselected">16:9 (1920×1080)</option>
                      <option v-if="selectedResolution === '1080p'" value="9:16" class="text-blue-aspectoptionselected">9:16 (1080×1920)</option>
                      <option v-if="selectedResolution === '1080p'" value="1:1" class="text-blue-aspectoptionselected">1:1 (1440×1440)</option>
                      <option v-if="selectedResolution === '1080p'" value="4:3" class="text-blue-aspectoptionselected">4:3 (1632×1248)</option>
                      <option v-if="selectedResolution === '1080p'" value="3:4" class="text-blue-aspectoptionselected">3:4 (1248×1632)</option>
                    </select>
                  </div>
                </div>
              </div>
                         <!-- Toggle Switches -->
             <div class="space-y-2 pb-2 border-b border-gray-200">
               <div class="flex justify-between items-center">
                 <label class="text-sm font-medium text-gray-700">Prompt Optimization</label>
                 <label class="relative inline-flex items-center cursor-pointer">
                   <input type="checkbox" v-model="optimizePrompt" class="sr-only peer">
                   <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-light rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-dark"></div>
                 </label>
               </div>
               
               <div class="flex justify-between items-center">
                 <label class="text-sm font-medium text-gray-700">Negative Prompt</label>
                 <label class="relative inline-flex items-center cursor-pointer">
                   <input type="checkbox" v-model="showNegativePrompt" class="sr-only peer">
                   <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-light rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-dark"></div>
                 </label>
               </div>
             </div>
            

            
                         <!-- Negative Prompt Input -->
             <div v-show="showNegativePrompt" class="pb-2 border-b border-gray-200">
               <label class="block text-sm font-medium text-gray-700 mb-2">Negative Prompt</label>
               <textarea 
                 v-model="negativePrompt"
                 rows="2" 
                 class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-dark focus:border-blue-dark resize-none transition-colors"
                 placeholder="e.g., blurry, watermark, text, low quality"
               ></textarea>
             </div>
            
                         <!-- Generate Button -->
             <button 
               type="submit" 
               class="w-full py-3 bg-blue-dark text-white font-medium rounded-lg hover:bg-blue-medium transition-colors duration-200"
               :disabled="isGenerating"
             >
              <span v-if="isGenerating">Generating...</span>
              <span v-else>Generate ({{ currentCreditCost }} Credits)</span>
            </button>
          </form>
        </div>

        <!-- Right Column: Preview -->
        <div class="bg-white rounded-xl border border-gray-200 p-8 flex flex-col items-center justify-center sticky top-8 min-h-[400px]">
          <svg class="w-12 h-12 text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10"></circle>
            <polygon points="10 8 16 12 10 16 10 8"></polygon>
          </svg>
          <p class="text-gray-600 font-medium">Your generated video will appear here</p>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useNuxtApp } from 'nuxt/app'
import { useClerkAuth } from '~/utils/authHelper'
import { useUserStore } from '~/stores/user'
import { useUiStore } from '~/stores/ui'
import { useRouter } from 'vue-router'

const { $toast } = useNuxtApp() as any
const { isSignedIn } = useClerkAuth()
const userStore = useUserStore()
const uiStore = useUiStore()
const router = useRouter()

// 响应式数据
const activeMode = ref('text-to-video')
const prompt = ref('')
const negativePrompt = ref('')
const optimizePrompt = ref(true)
const showNegativePrompt = ref(false)
const isGenerating = ref(false)
const uploadedImage = ref<File | null>(null)
const selectedResolution = ref('480p') // 新增分辨率选择
const selectedAspectRatio = ref('1:1') // 新增宽高比选择

// 用户积分计算
const userCredits = computed(() => {
  const userInfo = userStore.userInfo
  if (!userInfo) return 0
  return (userInfo.free_limit || 0) + (userInfo.remaining_limit || 0)
})

// 分辨率积分配置
const resolutionCreditConfig = {
  '480p': 20,
  '1080p': 100
}

// 当前积分消耗
const currentCreditCost = computed(() => {
  const resolution = selectedResolution.value
  return resolutionCreditConfig[resolution as keyof typeof resolutionCreditConfig] || 20
})

// 检查登录状态
const checkLoginStatus = async () => {
  // 每次都重新获取最新的用户信息
  await userStore.fetchUserInfo()
  
  // 检查用户是否已登录
  if (!userStore.userInfo) {
    uiStore.showLoginPrompt()
    return false
  }
  return true
}

// 验证提示词
const validatePrompt = () => {
  if (!prompt.value.trim()) {
    $toast.error('Please enter a prompt')
    return false
  }
  
  if (prompt.value.trim().length < 10) {
    $toast.error('Prompt must be at least 10 characters long')
    return false
  }
  
  if (prompt.value.trim().length > 1000) {
    $toast.error('Prompt must be less than 1000 characters')
    return false
  }
  
  return true
}

// 验证图片上传
const validateImageUpload = () => {
  if (activeMode.value === 'image-to-video' && !uploadedImage.value) {
    $toast.error('Please upload an image for image-to-video mode')
    return false
  }
  
  if (uploadedImage.value) {
    // 检查文件大小 (最大10MB)
    const maxSize = 10 * 1024 * 1024 // 10MB
    if (uploadedImage.value.size > maxSize) {
      $toast.error('Image file size must be less than 10MB')
      return false
    }
    
    // 检查文件类型
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp']
    if (!allowedTypes.includes(uploadedImage.value.type)) {
      $toast.error('Please upload a valid image file (JPEG, PNG, or WebP)')
      return false
    }
  }
  
  return true
}

// 模式切换
const switchMode = (mode: string) => {
  activeMode.value = mode
  // 切换模式时清空图片和重置宽高比
  if (mode === 'text-to-video') {
    uploadedImage.value = null
  } else if (mode === 'image-to-video') {
    uploadedImage.value = null
    selectedAspectRatio.value = '1:1'
  }
}

// 图片上传处理
const handleImageUpload = (event: Event) => {
  const target = event.target as HTMLInputElement
  if (target.files && target.files[0]) {
    uploadedImage.value = target.files[0]
  }
}

// 生成处理
const handleGenerate = async () => {
  // 1. 检查登录状态
  const isLoggedIn = await checkLoginStatus()
  if (!isLoggedIn) {
    return
  }

  // 2. 检查积分是否足够
  if (userCredits.value < currentCreditCost.value) {
    $toast.error(`Insufficient credits. This operation requires ${currentCreditCost.value} credits, but you only have ${userCredits.value} credits`)
    router.push('/pricing')
    return
  }

  // 3. 验证提示词
  if (!validatePrompt()) {
    return
  }

  // 4. 验证图片上传
  if (!validateImageUpload()) {
    return
  }

  // 5. 开始生成
  isGenerating.value = true
  
  try {
    // 模拟生成过程
    await new Promise(resolve => setTimeout(resolve, 3000))
    $toast.success('Video generated successfully!')
  } catch (error) {
    $toast.error('Generation failed. Please try again.')
  } finally {
    isGenerating.value = false
  }
}

// 监听分辨率变化，重置宽高比选择
watch(selectedResolution, (newResolution) => {
  if (newResolution === '480p') {
    selectedAspectRatio.value = '1:1'
  } else if (newResolution === '1080p') {
    selectedAspectRatio.value = '16:9'
  }
})

// 监听模式变化，重置宽高比选择
watch(activeMode, (newMode) => {
  if (newMode === 'image-to-video') {
    selectedAspectRatio.value = '1:1'
  }
})

// 组件挂载时获取用户信息
onMounted(() => {
  userStore.fetchUserInfo()
})
</script> 